 (function(){
  F1.WorldBank.extractives = {
  
  "Licenses": {
   infoWindowFilter:{"title": "$[soumnameen] Soum","subtitle": "","tabs": [{"title": "<b>үйлдвэрлэл</b>","type": "text","value": "ашиглалтын лиценцийн тоо: $[prod_count]\nашиглалтын лиценцитэй газар: $[prod_area] гектар\nсумын нутаг: $[soum_area] гектар\nсумын хувь: $[prod_pct]"},{"title": "<b>хайгууль</b>","type": "text","value": "хайгуулийн лиценцийн тоо: $[exp_count]\nхайгуулын лиценцтэй газар: $[exp_area] гектар\nсумын нутаг: $[soum_area] гектар\nсумын хувь: $[exp_pct]"},{"title": "<b>Нийт</b>","type": "text","value": "нийт лиценцийн тоо: $[all_count]\nлиценци бүхий газрууд: $[all_area] гектар\nсумын нутаг: $[soum_area] гектар\nсумын хувь: $[all_pct]"},{"title": "<b>тухай</b>","type": "text","value": "Лиценцийн орон зайн өгөгдөлийг Ашигт малтмалын хэрэг эрхлэх газраас, хил хязгаарын өгөгдөлийг Байгаль орчны мэдээллийн төвөөс авсан."}]},
  "Production percent": {"infoWindowFilter": {"subtitle": "ашиглалтын лиценцитэй сумын хувь: $[prod_pct]%"},"icon": {"opacity": 0.75,"size": 1,"symbol": "propCircle","propSize": null,"classificationType": "Quantile","gradSize": 1,"dropShadow": true,"selectedAttribute": "prod_pct","categories": 5, "color": [0xFEF7A5]},"type": "GRADUATED","stroke": {"alpha": 1,"weight": 1,"color": [0xFEF7A5]},"fill": {"opacity": 0.75,"color": [0xFEF7A5]}, "expression":"$[prod_pct] > 0"},
  "Production count": {"infoWindowFilter": {"subtitle": "сум дахь ашиглалтын лиценцийн тоо: $[prod_count]"},"icon": {"opacity": 0.75,"size": 1,"symbol": "propCircle","propSize": null,"classificationType": "Quantile","gradSize": 1,"dropShadow": true,"selectedAttribute": "prod_count","categories": 5,"color": [0xFCAE91]},"type": "GRADUATED","stroke": {"alpha": 1,"weight": 1,"color": [0xFCAE91]},"fill": {"opacity": 0.75,"color": [0xFCAE91]}, "expression":"$[prod_count] > 0"},
  "Exploration percent": {"infoWindowFilter": {"subtitle": "ашиглалтын лиценцитэй сумын хувь: $[exp_pct]%"}, "icon": {"opacity": 0.75,"size": 1,"symbol": "propCircle","propSize": null,"classificationType": "Quantile","gradSize": 0.75,"dropShadow": true,"selectedAttribute": "exp_pct","categories": 5,"color": [0xFECE6D]},"type": "GRADUATED","stroke": {"alpha": 1,"weight": 1,"color": [0xFECE6D]},"fill": {"opacity": 0.75,"color": [0xFECE6D]}, "expression":"$[exp_pct] > 0"},  
  "Exploration count": {"infoWindowFilter": {"subtitle": "сумын хайгуулын лиценцийн тоо: $[exp_count]"},"icon": {"opacity": 0.75,"size": 1,"symbol": "propCircle","propSize": null,"classificationType": "Quantile","gradSize": 0.75,"dropShadow": true,"selectedAttribute": "exp_count","categories": 5,"color": [0xFB6A4A]},"type": "GRADUATED","stroke": {"alpha": 1,"weight": 1,"color": [0xFB6A4A]},"fill": {"opacity": 0.75,"color": [0xFB6A4A]},"expression":"$[exp_count] > 0"},
  "All percent": {"infoWindowFilter": {"subtitle": "аль нэг лиценци бүхий сумын хувь: $[all_pct]%"},"icon": {"opacity": 0.75,"size": 1,"symbol": "propCircle","propSize": null,"classificationType": "Quantile","gradSize": 1,"dropShadow": true,"selectedAttribute": "all_pct","categories": 5, "color": [0xEC8414]},"type": "GRADUATED","stroke": {"alpha": 1,"weight": 1,"color": [0xEC8414]},"fill": {"opacity": 0.75,"color": [0xEC8414]},"expression":"$[all_pct] > 0"},
  "All count": {"infoWindowFilter": {"subtitle": "сумын нийт лиценцийн тоо: $[all_count]"},"icon": {"opacity": 0.75,"size": 1,"symbol": "propCircle","propSize": null,"classificationType": "Quantile","gradSize": 1,"dropShadow": true,"selectedAttribute": "all_count","categories": 5,"color": [0xCB181D]},"type": "GRADUATED","stroke": {"alpha": 1,"weight": 1,"color": [0xCB181D]},"fill": {"opacity": 0.75,"color": [0xCB181D]},"expression":"$[all_count] > 0"}
  },
  
  "EITI": {
   infoWindowFilter:{"title": "$[soumnameen] Soum, $[aimagnameen] Aimag","subtitle":"","tabs": [{"title": "<b>төлбөрүүд</b>","type": "text","value": "төлбөрийн өгөгдөлийн хураангуй, сумаар.\nнийт төлбөр: $[totalpaysum] мянган төгрөг\nулсын төсөвт оруулсан: $[centralpaysum] мянган төгрөг\nорон нутгийн төсөвт оруулсан: $[localpaysum] мянган төгрөг"},{"title": "<b>ашигт малтмал</b>","type": "text","value": "суманд олборлож байгаа ашигт малтмал\nалт: $[gold]\nзэс: $[copper]\nтөмөр: $[iron]\nнүүрс: $[coal]\nгазрын тос: $[petroleum]\nбусад: $[other]\nбусад ашигт малтмалд: молибден, жонш, уран, лигнит, цинк, сульфат, чулуу болон барилгын материал хамрагдана"},{"title": "<b>компаниуд</b>","type": "text","value": "энэ суманд тайлагнаж байгаа компаниуд, тэдний бүртгэлийн дугаар:\n$[complistpay]"},{"title": "<b>тухай</b>","type": "text","value": "Төлбөрийн өгөгдөлийг ОҮИС 2010 оны тайлангаас авч, компаниудын олборлолт хийж байгаа сумуудтай нэгэтгэсэн. Зөвхөн нэг суманд ажиллаж байгаа компаниудыг оруулсан."}]},
   "National payments":  {"infoWindowFilter": {"subtitle": "улсын төсвөт оруулсан төлбөрийн дүн: $[centralpaysum] мянган төгрөг"},"icon": {"opacity": 0.75,"size": 1,"symbol": "propCircle","propSize": null,"classificationType": "Quantile","gradSize": 1,"dropShadow": true,"selectedAttribute": "centralpaysum","categories": 5, "color": [0xEBD9C2]},"type": "GRADUATED","stroke": {"alpha": 1,"weight": 1,"color": 137011},"fill": {"opacity": 0.75,"color": [0xEBD9C2]},"expression":"$[centralpaysum] > 0"},
  "Local payments":  {"infoWindowFilter": {"subtitle": "орон нутгийн төсөвт оруулсан төлбөрийн дүн: $[localpaysum] мянган төгрөг"},"icon": {"opacity": 0.75,"size": 1,"symbol": "propCircle","propSize": null,"classificationType": "Quantile","gradSize": 1,"dropShadow": true,"selectedAttribute": "localpaysum","categories": 5,"color": [0xD1B79F]},"type": "GRADUATED","stroke": {"alpha": 1,"weight": 1,"color": 137011},"fill": {"opacity": 0.75,"color": [0xD1B79F]},"expression":"$[localpaysum] > 0"},
  "Total payments":  {"infoWindowFilter": {"subtitle": "нийт төлбөрийн дүн: $[totalpaysum] мянган төгрөг"},"icon": {"opacity": 0.75,"size": 1,"symbol": "propCircle","propSize": null,"classificationType": "Quantile","gradSize": 1,"dropShadow": true,"selectedAttribute": "totalpaysum","categories": 5,"color": [0xA4866D]},"type": "GRADUATED","stroke": {"alpha": 1,"weight": 1,"color": 137011},"fill": {"opacity": 0.75,"color": [0xA4866D]},"expression":"$[totalpaysum] > 0"}
  },
 
 "Company": {
   infoWindowFilter:{"title": "$[company_name]","subtitle":"", "tabs": [{"title": "<b>компаний мэдээлэл</b>","type": "text","value": "компаний нэр: $[company_name]\nбүртгэлийн дугаар:: $[registration_number]\nхөрөнгө оруулалтын хэлэлцээр: $[invest_agree]"},{"title": "<b>ашигт малтмал</b>","type": "text","value": "суманд олборлож байгаа ашигт малтмал\nалт: $[gold]\nзэс: $[copper]\nтөмөр: $[iron]\nнүүрс: $[coal]\nгазрын тос: $[petroleum]\nбусад: $[other]\nбусад ашигт малтмалд: молибден, жонш, уран, лигнит, цинк, сульфат, чулуу болон барилгын материал хамрагдана"},{"title": "<b>тухай</b>","type": "text","value": "Компаний мэдээллийг 2010 оны ОҮИС тайлангаас авсан, компаниуд олборлолт явуулж байгаа бүх сумыг оруулсан."}]},
   "Location":  {"infoWindowFilter": {"subtitle": "ОҮИС 2010 төлбөрийн дүн: $[totalpay] мянган төгрөг"},"type": "PRIMITIVE","stroke": {"color": [0x361E18], "weight": 1, "opacity": 0.75},"fill":{"color":[0x543E36],"opacity": 0.75}},
  },

 "Donations": {
   infoWindowFilter:{"title": "$[soumnameen] Soum, $[aimagnameen] Aimag","subtitle":"","tabs": [{"title": "<b>өгөгдөл</b>","type": "text","value": "Сумын түвшинд хийсэн хандивын дүн.\nхандив: $[donation_sum] мянган төгрөг\nбайгаль орчны санд оруулсан хувь нэмэр: $[envcontrib_sum] мянган төгрөг\nорон нутгийн татвар, хураамжууд г.м: $[payment_sum] мянган төгрөг\nгүйлгээний тоо: $[transaction_number]"},{"title": "<b>тухай</b>","type": "text","value": "орон нутгийн байгаль орчны санд нөхөн сэргээлт, орон нутгийн үйл ажиллагаанд өгсөн хандивууд, орон нутгийн татварууд, хураамжууд, роялти зэрэгт төлсөн төлбөрүүдийн мэдээллийг компаниуд сайн дураараа өгсөн"}]},
   "Transaction count":  {"infoWindowFilter": {"subtitle": "нийт хийгдсэн гүйлгээ: $[transaction_number]"},"icon": {"opacity": 0.75,"size": 1,"symbol": "propCircle","propSize": null,"classificationType": "Quantile","gradSize": 1,"dropShadow": true,"selectedAttribute": "transaction_number","categories": 5, "color": [0x361E18]},"type": "GRADUATED","stroke": {"alpha": 1,"weight": 1,"color": 137011},"fill": {"opacity": 0.75,"color": [0x361E18]}},
  "Total donations":  {"infoWindowFilter": {"subtitle": "суманд өгсөн нийт хандивын дүн: $[donation_sum] мянган төгрөг"},"icon": {"opacity": 0.75,"size": 1,"symbol": "propCircle","propSize": null,"classificationType": "Quantile","gradSize": 1,"dropShadow": true,"selectedAttribute": "donation_sum","categories": 5,"color": [0x7C6253]},"type": "GRADUATED","stroke": {"alpha": 1,"weight": 1,"color": 137011},"fill": {"opacity": 0.75,"color": [0x7C6253]}},
  "Environmental contributions":  {"infoWindowFilter": {"subtitle": "байгаль орчны санд оруулсан төлбөрийн дүн: $[envcontrib_sum] мянган төгрөг"},"icon": {"opacity": 0.75,"size": 1,"symbol": "propCircle","propSize": null,"classificationType": "Quantile","gradSize": 1,"dropShadow": true,"selectedAttribute": "envcontrib_sum","categories": 5,"color": [0x4A342C]},"type": "GRADUATED","stroke": {"alpha": 1,"weight": 1,"color": 137011},"fill": {"opacity": 0.75,"color": [0x4A342C]}}
  },

 "Special Protected Areas": {
   infoWindowFilter:{"title": "$[placenamee] байгаль орчны санд оруулсан төлбөрийн дүн","subtitle":"","tabs": [{"title": "<b>өгөгдөл</b>","type": "text","value": "Тусгай хамгаалалттай газруудын хил хязгаарын мэдээллийг Байгаль орчны мэдээллийн төв өгсөн"}]},
   "Location":  {"infoWindowFilter": {"subtitle": ""},"type": "PRIMITIVE","stroke": {"color": [0x238443], "weight": 1, "opacity": 0.75},"fill":{"color":[0x238443],"opacity": 0.75}},
  },

"Forest": {
   infoWindowFilter:{"title": "ой модтой газрууд","subtitle":"","tabs": [{"title": "<b>тухай</b>","type": "text","value": "Монгол дахь ой модтой газруудын хамааруулалт. Өгөгдөлийг Байгаль орчны мэдээллийн төв өгсөн."}]},
   "Location":  {"infoWindowFilter": {"subtitle": ""},"type": "PRIMITIVE","stroke": {"color": [0x005A32], "weight": 1, "opacity": 0.75},"fill":{"color":[0x005A32],"opacity": 0.75}},
  },

  "Infant Mortality": {source: "finder:", title:"нярайн эндэгдэлийн хувь", subtitle: "1000 амьд төрөлтөд \\аймгаар\\", styles: { type: "CHOROPLETH", stroke: {color: 0x222222}, fill: { colors: [0xFEF7A5, 0xFECE6D, 0xEC8414, 0xAE4C02, 0x662506], categories: 5, classificationNumClasses: 5, classificationType: "QUANTILE", opacity: 0.75, selectedAttribute: "infantmort"}}, infosubtitle: null, table: null, description: "2012 оны 2 дугаар улиралын байдлаар 1000 амьд төрөлтөд ноогдох нярайн эндэгдэл. Нярайн эндэгдэл гэдэг нь нялх хүүхдийн нас баралтын хувь \\нэг нас хүрэхээс өмнө\\ судалгаанаас өмнөх арван жил.\nэх сурвалж: <a href='http://www.nso.mn/v3/index2.php?page=free_access' target='_new'>Улсын Статистикийн газарь Монгол</a>."},
  
  "Population": {source: "finder:", title:"хүн ам", subtitle: "хүн амын тоо", styles: { type: "CHOROPLETH",stroke: {color: 0x222222}, fill: { colors: [0xEFF3FF, 0xBDD7E7, 0x6BAED6, 0x3182BD, 0x08519C], categories: 5, classificationNumClasses: 5, classificationType: "QUANTILE", opacity: 0.75, selectedAttribute: "population"}}, infosubtitle: "$[aimagnamemn] аймаг бүрийн хүн амын тоо", table: null, description: "2010 оны байдлаар $[aimagnamemn] аймаг бүрийн хүн ам.\nэх сурвалж: <a href='http://www.nso.mn/v3/index2.php?page=free_access' target='_new'>Улсын Статистикийн газарь Монгол</a>."},
  
  "Unemployment": {source: "finder:", title:"ажилгүйдэл", subtitle: "", styles: { type: "CHOROPLETH", stroke: {color: 0x222222}, fill: { colors: [0xFEE5D9, 0xFCAE91, 0xFB6A4A, 0xDE2D26, 0xA50F15], categories: 5, classificationNumClasses: 5, classificationType: "QUANTILE", opacity: 0.75, selectedAttribute: "unemployment"}}, infosubtitle: "2010 оны эхний хагаст $[aimagnamemn] аймаг бүрт ажил эрхлээгүй хүний тоо", table: null, description: "2010 оны эхний хагаст $[aimagnamemn] аймаг бүрт ажил эрхлээгүй хүний тоо. эх сурвалж: <a href='http://www.nso.mn/v3/index2.php?page=free_access' target='_new'>Улсын Статистикийн газарь Монгол</a>."},
  
  "Number of Physicians": {source: "finder:", title:"их эмч нарын тоо", subtitle: "", styles: { type: "CHOROPLETH", stroke: {color: 0x222222}, fill: { colors: [15456706, 13744031, 10782317, 8151635, 4863020], categories: 5, classificationNumClasses: 5, classificationType: "QUANTILE", opacity: 0.75, selectedAttribute: "physnum"}}, infosubtitle: "$[aimagnamemn] аймаг бүрийн их эмч нарын тоо", table: null, description: "аймаг бүрт байгаа их эмч нарын тоо, 2010 оны байдлаар. \nэх сурвалж: <a href='http://www.nso.mn/v3/index2.php?page=free_access' target='_new'>Улсын Статистикийн газарь Монгол</a>."},
  
  "Number of Households": {source: "finder:", title:"өрхийн тоо \\мянгаар\\", subtitle: "", styles: { type: "CHOROPLETH", stroke: {color: 0x222222}, fill: { colors: [5313667, 8608676, 12619965, 14924738, 16573399], categories: 5, classificationNumClasses: 5, classificationType: "QUANTILE", opacity: 0.75, selectedAttribute: "housenum"}}, infosubtitle: "$[aimagnamemn] аймгийн өрхийн тоо \\мянгаар\\", table: null, description: "аймаг бүрийн хүн амын тоо, 2010 оны байдлаар. \nэх сурвалж: <a href='http://www.nso.mn/v3/index2.php?page=free_access' target='_new'>Улсын Статистикийн газарь Монгол</a>."},
  
  "Soum Boundaries":{source: "finder:", title:"$[soumnameen] Soum, $[aimagnameen] Aimag", selectedAttribute:"soumnameen",subtitle: "",styles: {type: "PRIMITIVE",stroke: {color: 0x222222, weight: 1, opacity: 0.75},fill:{color:[0xCCCC66],opacity: 0.75}},infosubtitle: "$[soumnameen] Soum", table: null, description: "Сумдын хил хязгаарыг Байгаль орчны мэдээллийн төвөөс авсан."},
  
  };
  })();
